language: php

php:
  - 5.3
  - 5.5

env:
  global:
      - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
  matrix:
      - WP_VERSION=latest 
      - WP_VERSION=3.4.2

matrix:
  exclude:
    - php: 5.5
      env: WP_VERSION=3.4.2

before_script: ./bin/ci/prepare.sh

script: ./bin/ci/build.sh

notifications:
  email:
    on_success: never
